# Generated by Django 5.2.16 on 2026-08-14 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
        ("crm_leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="academics.batch",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="academics.course",
            ),
        ),
    ]
