# Generated by Django 5.2.16 on 2026-09-13 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_course_field_of_engineering"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="teachers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Teachers assigned to this cohort (primary, co-teachers, or substitutes).",
                related_name="assigned_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="conducted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Teacher who actually conducted the lecture and marked attendance (allows substitutes).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conducted_lectures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
