# Generated by Django 5.2.16 on 2026-09-11 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_course_field_of_engineering"),
        ("communications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="academics.batch",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("STUDENTS", "Students"),
                    ("PARENTS", "Parents"),
                    ("ALL", "Students & Parents"),
                ],
                default="STUDENTS",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("IN_APP", "In-App"),
                    ("SMS", "SMS"),
                    ("EMAIL", "Email"),
                    ("ALL", "All Channels"),
                ],
                default="IN_APP",
                max_length=20,
            ),
        ),
    ]
