# Generated by Django 5.2.16 on 2026-10-05 04:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0003_devicetoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "template_key",
                    models.CharField(db_index=True, max_length=60, unique=True),
                ),
                ("meta_template_name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("UTILITY", "Utility (Class alerts, fees, attendance)"),
                            ("MARKETING", "Marketing (Promotions, new courses)"),
                            (
                                "AUTHENTICATION",
                                "Authentication (OTPs, password resets)",
                            ),
                        ],
                        default="UTILITY",
                        max_length=20,
                    ),
                ),
                ("language_code", models.CharField(default="en_US", max_length=10)),
                (
                    "header_type",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("TEXT", "Text Header"),
                            ("DOCUMENT", "PDF Document (Receipts, Reports)"),
                            ("IMAGE", "Image (Schedules, Notices)"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("body_text_sample", models.TextField(blank=True, default="")),
                ("parameter_schema", models.JSONField(default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("IN_APP", "In-App"),
                    ("SMS", "SMS"),
                    ("EMAIL", "Email"),
                    ("WHATSAPP", "WhatsApp"),
                    ("ALL", "All Channels"),
                ],
                default="IN_APP",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WhatsAppPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "whatsapp_phone",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="E.164 formatted WhatsApp number (e.g. +919876543210)",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_whatsapp_verified", models.BooleanField(default=False)),
                (
                    "opt_in_transactional",
                    models.BooleanField(
                        default=True,
                        help_text="Consent for academic, fee, and operational alerts",
                    ),
                ),
                (
                    "opt_in_marketing",
                    models.BooleanField(
                        default=False,
                        help_text="Consent for promotional workshops, courses, and offers",
                    ),
                ),
                (
                    "consent_source",
                    models.CharField(
                        choices=[
                            ("ADMISSION_FORM", "Admission Form / Agreement"),
                            ("STUDENT_PORTAL", "Self-service Portal / App"),
                            ("STAFF_ENTRY", "Staff Administrative Entry"),
                            ("INBOUND_MSG", "Inbound WhatsApp Message (Opt-in)"),
                        ],
                        default="ADMISSION_FORM",
                        max_length=30,
                    ),
                ),
                (
                    "consent_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "opted_out_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "opt_out_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="WhatsAppDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "recipient_role",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student"),
                            ("PARENT", "Parent"),
                            ("STAFF", "Staff"),
                        ],
                        default="STUDENT",
                        max_length=20,
                    ),
                ),
                (
                    "phone_snapshot",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("template_name", models.CharField(max_length=120)),
                ("template_parameters", models.JSONField(default=dict)),
                (
                    "header_media_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("provider", models.CharField(default="META_CLOUD", max_length=30)),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Enqueue"),
                            ("QUEUED", "Queued in Worker"),
                            ("SUBMITTED", "Submitted to Meta"),
                            ("SENT", "Sent (Carrier Accepted)"),
                            ("DELIVERED", "Delivered to Handset"),
                            ("READ", "Read by Recipient"),
                            ("FAILED", "Delivery Failed"),
                            ("SKIPPED", "Skipped (No number / No consent / Opted out)"),
                            ("OPTED_OUT", "Suppressed (User previously opted out)"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=50, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "pricing_category",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "idempotency_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_deliveries",
                        to="communications.notification",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="communications.whatsapptemplate",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="wa_delivery_status_idx"
                    ),
                    models.Index(
                        fields=["recipient", "status"],
                        name="wa_delivery_recip_status_idx",
                    ),
                ],
            },
        ),
    ]
