# Generated by Django 5.2.16 on 2026-10-05 04:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0004_whatsapptemplate_alter_notification_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="campaign_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
