# Generated by Django 5.2.16 on 2026-08-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_photo_and_audit_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user", options={"ordering": ["first_name", "last_name", "username"]},
        ),
    ]
